name: "🖊️ Sign the Guestbook"
description: Add your avatar to my pixel grid!
title: "Guestbook Signature"
labels: ["guestbook"]
body:
  - type: markdown
    attributes:
      value: |
        ## Add your avatar to the pixel grid on [my GitHub profile](https://github.com/timoseyfarth)!
        
        By submitting this issue, a GitHub Action will automatically fetch your avatar, downscale it to one pixel and add it to the guestbook [my GitHub profile](https://github.com/timoseyfarth).
  
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I hereby consent to be pixelated! 👾
          required: true
          
  - type: checkboxes
    id: anonymous_mode
    attributes:
      label: Privacy Preference (Optional)
      options:
        - label: Make me anonymous (hide my username on hover on the grid).
    validations:
      required: false

  # --- FUN / OPTIONAL SECTION ---
  - type: markdown
    attributes:
      value: |
        ---
        ### Optional Fun Section
        Everything below this is optional and just for fun. Some inputs may be displayed on hover of your pixel.

  - type: dropdown
    id: editor_war
    attributes:
      label: The Editor War (Optional)
      description: How do you write your code?
      options:
        - "VS Code (I love plugins more than code)"
        - "JetBrains IDE (My laptop fan is a jet engine)"
        - "Vim / Neovim (I don't know how to exit)"
        - "Eclipse (When is the last time you cleaned your workspace?)"
        - "Notepad (I am a psychopath)"
    validations:
      required: false
  
  - type: input
    id: quote
    attributes:
      label: Drop a Quote (Optional)
      description: A short wisdom, a joke, or your favorite "it works on my machine" moment.
      placeholder: "Real programmers count from 0."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ### Usage Information
        
        This guestbook is **fully automated** by a [backend server](https://github.com/timoseyfarth/guestbook-pixel-server).
        
        * **To Sign:** Simply fill out the fields and submit.
        * **To Update:** You have a new profile picture, want to change your quote, or editor choice? **Just submit a new issue.** The system will automatically update your existing entry on the grid.
        * **To Remove:** If you want your data completely deleted, please contact me directly via [email](mailto:timo@seyfarth.dev).
